### ISSUE TITLE
Project: CodeStyle file

### ISSUE THREAD

**Issue by kvithayathil** [SoftwareEngineeringDaily/SEDaily-Android#12]
We should agree upon a code style that we can use to enforce consistency.

**The options are:**
- [Square's Java code styles](https://github.com/square/java-code-styles)
- [AndroidStyle from the AOSP Project](https://github.com/android/platform_development/blob/master/ide/intellij/codestyles/AndroidStyle.xml)

Let me know your thoughts

**Comment by TheHollidayInn** [comment]
I saw you used Square's I tried theirs out, and I like it. I opened a PR to fix lint issues.
