### ISSUE TITLE
Feature: Add share buttons

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/SEDaily-Android#15]

**Comment by jaketothepast** [comment]
Hey! Thanks for maintaining this project the app is awesome! I wanted to tackle this issue but being entirely new to Android development, I realized I implemented a share button which has a share intent, vs. having share button(s) plural. Should I keep going down the route I started on and submit the PR? I almost have it complete but I don't want to waste anyone's time.

**Comment by TheHollidayInn** [comment]
Hey! Thanks for taking this on :) a share button opening the share intent is my preference so keep at it!
