### ISSUE TITLE
Feature: Vector SDE logo for use in-app

### ISSUE THREAD

**Issue by kvithayathil** [SoftwareEngineeringDaily/SEDaily-Android#22]
We should use an android vector drawable for the SDE logo (not launcher). That way, the system will automatically scale to the right DPI

**Comment by kvithayathil** [comment]
You can find some examples in my share drive [here](https://drive.google.com/drive/folders/0BzVFpvJR4V1xYm5sWXFrMWxRaTQ?usp=sharing).

Note: I'm not a gfx designer :)

**Comment by TheHollidayInn** [comment]
Ah, yes. Thanks for posting this.
