### ISSUE TITLE
master branch not compiling

### ISSUE THREAD

**Issue by itaykomemy** [SoftwareEngineeringDaily/SEDaily-Android#23]
master branch not compiling because of a missing component, namely:
com.koalatea.thehollidayinn.softwareengineeringdaily.mediaui.PlaybackControlsFragment
imported in PlaybackControllerActivity

**Comment by Tofuus** [comment]
I'm having the same issue. Here's a [pastebin ](https://pastebin.com/fLAuyEEp) of the log output.

I'm using Windows 10. Latest commit  6370f7f. I ran `./gradlew build`

**Comment by TheHollidayInn** [comment]
Sorry. This was just a mismanage of Git on my part. I’ll push the update soon.

**Comment by itaykomemy** [comment]
Still no go,
on develop branch:
Error:No resource found that matches the given name (at 'fullBackupContent' with value '@xml/backup_descriptor').

**Comment by TheHollidayInn** [comment]
Turns out I just need to add the full App directory and reset the cache. That was my mistake when preparing release. I have another PR coming soon. Sorry all

**Comment by TheHollidayInn** [comment]
Try now please.

**Comment by Tofuus** [comment]
It's fixed for me now. Note that you'll need to generate a `google-services.json` through Firebase. Checkout the WIP readme for instructions on how to do that.

https://github.com/Tofuus/SEDaily-Android/tree/readme

**Comment by TheHollidayInn** [comment]
Awesome! And thanks for the PR. I’ll read over it.
