### ISSUE TITLE
Episode shows 585 hours remaining

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/SEDaily-Android#25]
![image](https://user-images.githubusercontent.com/1283090/31501883-572d8b00-af20-11e7-85f1-083e7ee58b19.png)

**Comment by Tofuus** [comment]
Unable to replicate on the developer branch. Attempted listening to the same episode for about a minute.

**Comment by TheHollidayInn** [comment]
This is fixed in develop branch because it downloads the podcast first. I need to fix the UI before marking this completed.
