### ISSUE TITLE
Search not working correctly

### ISSUE THREAD

**Issue by bholagabbar** [SoftwareEngineeringDaily/SEDaily-Android#28]
The search doesn't work as expected. Here's a screenshot of me searching for the docker Networking podcast but it doesn't seem to be turning up 

![](https://i.imgur.com/jpNvjUC_d.jpg)

**Comment by samuelrey** [comment]
What happens when you search 'Ethereum Platform with...'?

**Comment by bholagabbar** [comment]
Erm pretty much the same? ![](https://i.imgur.com/M7m50VI.jpg)

**Comment by samuelrey** [comment]
Did the app crash at all?
I noticed that the Ethereum podcast showed up in both results; are they subsets of each other?

**Comment by bholagabbar** [comment]
Nope the app didn't crash. The ethereum podcast keeps showing because it's the latest one. It seems that the search has no effect and it shows the latest podcasts (which it shows by default as it is)

**Comment by Tofuus** [comment]
I believe this is because search isn't implemented on the API side yet. So it just shows the latest podcasts.

**Comment by TheHollidayInn** [comment]
Search is on the API. I'll investigate there. We have an open issue to improve search on the API

**Comment by samuelrey** [comment]
Is the desired behavior for search documented somewhere?

**Comment by bholagabbar** [comment]
Is anyone working on improving the search currently? I'd like to help, if it's on the API side.

**Comment by TheHollidayInn** [comment]
What do you mean by documented? @samuelrey. It’s part of the API so we will
Document it with the API docs

@bholagabbar we would love help. Have you checked out the api repo?

**Comment by bholagabbar** [comment]
@TheHollidayInn Yes I did. I checked out the routes and controllers folders but afa I noticed, there's not endpoint for search. As per my understanding, the API doesn't support search yet so it's yet to be implemented. Is that correct ?

**Comment by TheHollidayInn** [comment]
@bholagabbar Nah search is definitely on the API. Here you go: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/master/server/models/post.model.js#L88.

However, I don't really like the $text based mongo search because it requires full words. We have an open issue to improve search: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/issues/35.

If you want to take that on, let me know :D

**Comment by bholagabbar** [comment]
@TheHollidayInn Gotcha. I missed the models folder back then. Also went through methods and statics in Mongoose. Yeah I'll take this on.  I saw the issue as well. 

Does `Post` seem like good entity to you? Ideally you'd like to have a `User` entity (model, as we'd like to call it in Express), then an `Episode` model and then routes that handle something like `/episodes?search="stuff"`. What do you think?

**Comment by TheHollidayInn** [comment]
We do have a User entity, and the current url is something like `/api/v1/posts?search=stuff` which is similar to what you are saying.

I think your question is to whether or not the `Post` name is a good name for the episodes, and I would say no, it is not. Right now, the Post entity corresponds to the WP posts. We have plans to migrate away from WordPress and at that time we will create a new entity name Episodes to replace the Posts.

**Comment by bholagabbar** [comment]
Ah, that makes a lot more sense now. Thanks for the clarification. I'll go ahead and comment on https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/issues/35 and close this issue for now
