### ISSUE TITLE
[UI/UX] Feature: Visual Indicators for Episodes

### ISSUE THREAD

**Issue by Tofuus** [SoftwareEngineeringDaily/SEDaily-Android#36]
Things like **Watched**, **Watching**, **Downloaded** should have a visual indicator on the episode cards.

Watched - Remove the card?
Watching - [Yellow eye symbol ](http://coacentral.org/wp-content/uploads/2015/07/eye-yellow.png)
Downloading - Grey out the entire card
Downloaded - [Green download icon](http://icons.iconarchive.com/icons/double-j-design/origami-colored-pencil/256/green-document-download-icon.png)

I'm pretty bad at UI. Hopefully someone has better ideas.

**Comment by TheHollidayInn** [comment]
Good idea. Let's get some design inspiration first, but you have a good start going.

**Comment by TheHollidayInn** [comment]
Downloaded is now marked, watched will be done in #18
