### ISSUE TITLE
Project: Deprecate & Remove RxJava 1.0 Dependency

### ISSUE THREAD

**Issue by kvithayathil** [SoftwareEngineeringDaily/SEDaily-Android#41]
Right now we have both RxJava 1.x and 2.x added to the app. As we update the app we should make an effort to implement RxJava 2.x while removing usages of 1.x (and eventually the dependency).

**Comment by TheHollidayInn** [comment]
Doesn’t StorIO only use RXjava 1 right now?

**Comment by kvithayathil** [comment]
Yes, that's true.  We could resolve that by using storIO non-reactively and wrap it with our own RxJava 2.0-based Persistence facade. (This would also give us a bit more flexibility if ever we want to change how we persist data)

**Comment by TheHollidayInn** [comment]
Sounds like a great way to handle the issue.
