### ISSUE TITLE
Feature: Wrapper to encapsulate Firebase Analytics 

### ISSUE THREAD

**Issue by kvithayathil** [SoftwareEngineeringDaily/SEDaily-Android#42]
We should try and encapsulate the Firebase analytics in a wrapper interface. This interface would expose typical actions that the app would call to send to the analytics.

This would insulate the rest of the app from any changes to the underlying analytics engine while maintaining testability

**Comment by TheHollidayInn** [comment]
SOunds good. Definitely needs the facade pattern
