### ISSUE TITLE
Bug: Episode fails to on the first try

### ISSUE THREAD

**Issue by Tofuus** [SoftwareEngineeringDaily/SEDaily-Android#46]
After downloading an episode for the first time, the play button does not immediately start the episode. Instead you need to go back to the main screen and click the episode again. Only then does the episode start.

Device: One Plus 5
Android OS: 7.1.1
SED Version: Latest develop branch

**Comment by TheHollidayInn** [comment]
This is the current intention. I had to merge my branch before I  finished the UI. What I am trying to replicate is the download flow from the Apple podcast app:
1. Download button appears if the episode is not downloaded
2. User clicks download and progress appears
3. Download is completed, and user is notified via notification
4. User now sees the play button.
