### ISSUE TITLE
Architecture: Add Realm Caching

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/SEDaily-Android#5]

**Comment by TheHollidayInn** [comment]
We can also try Room with the new Android Architecture Components

**Comment by kvithayathil** [comment]
I'm thinking we start with SQL (either room, sqlbrite or storIO) unless we really need something in particular from realm

**Comment by TheHollidayInn** [comment]
Any reason you would rather have Room over Realm?

**Comment by kvithayathil** [comment]
Not necessarily Room in particular, but realm seems a bit heavy-weight compared to using the in-built SQL DB. While SQL is verbose I find it a bit easier to wrap it around testable code. Also, it avoids having to use realm objects. But my experience with realm is limited so maybe that's changed.

**Comment by TheHollidayInn** [comment]
I've been looking into StorIO. I like that as well. I think I am more for trying a lightweight SQL solution. Room or StorIO are my current picks.

**Comment by kvithayathil** [comment]
Cool, I've used StorIO and its been pretty good for me in the past. Room is interesting but still beta. Since its all SQL-based it should make for an easier process if we change our minds on the lib we use.

**Comment by kvithayathil** [comment]
Looks like Room is now 1.0 so it would be worth deciding if we use that or StorIO. Also we'll need to decide upon the schema (maybe as a separate ticket)

**Comment by TheHollidayInn** [comment]
Yea, I'm really liking Room now. The setup seems a bit easier.

**Comment by TheHollidayInn** [comment]
Coming up.
