### ISSUE TITLE
Feature: Migrating MediaStyle notifications to support Android O

### ISSUE THREAD

**Issue by kvithayathil** [SoftwareEngineeringDaily/SEDaily-Android#52]
Looking at the [next support library (27.x)](https://developer.android.com/topic/libraries/support-library/revisions.html#27-0-0), it looks like they're deprecating this current implementation of creating a media notification. This will impact the code at [this line](https://github.com/SoftwareEngineeringDaily/SEDaily-Android/blob/d39f760e286d971d5e0753f8b612043c7e7cb4b8/app/src/main/java/com/koalatea/thehollidayinn/softwareengineeringdaily/audio/MediaNotificationHelper.java#L145).

See [this article](https://medium.com/google-developers/migrating-mediastyle-notifications-to-support-android-o-29c7edeca9b7) for hints/suggestions on how to update.

**Comment by TheHollidayInn** [comment]
Looks good. This is probably a high priority then. Channels seem to be required for notifications.
