### ISSUE TITLE
Episode length wrong when playing episode

### ISSUE THREAD

**Issue by tobiasorth1** [SoftwareEngineeringDaily/SEDaily-Android#55]
## Device Details
- Device Name: Xiaomi Redmi Pro 4
- Android Version: 7.0
- App Version: 1.1

## Steps to Reproduce:
1. Open app
2. Choose episode and play
3. Episode length shown "563:58:45"
4. It is not possible to scroll through the episode (like starting on 00:05:00)
5. When you scroll, you end up somewhere like "163:00:00"
6. Episode stops playing
7. Pressing play will trigger playing episode but instantly ends playing again. Possibly due to trying to resume on time chosen in step 5

**Comment by TheHollidayInn** [comment]
Thanks for posting! This is fixed in the current dev build.
