### ISSUE TITLE
Feature: Settings Page

### ISSUE THREAD

**Issue by Tofuus** [SoftwareEngineeringDaily/SEDaily-Android#58]
Some ideas for categories

- Account
- Playback
    - Amount to seek forward or backwards
    - Control what media button combos do. e.g double press = skip forward.
- Notifications
    - Notify for all episodes vs ones with specific tags
    - Vibrate?
    - Notification sounds
- Download
    - Auto download new episodes?
    - Space quota
    - Choose where podcasts are saved
    - Allow download over mobile data
- Appearance
    - Dark mode?
- Storage
    - View how much space is being taken up
- Stats
    - You've listened to x topic for y hours
    - You've listened for x amount of hours

**Comment by TheHollidayInn** [comment]
Another great suggestion. This definitely has many features in it. So we would need to decide on which features, then implement them one at a time.

**Comment by GitTom** [comment]
How about, instead of:

Stats
* You've listened to x topic for y hours
* You've listened for x amount of hours

Have a history page just showing which episodes have been listened to (and when).  Just an activity log, really.

**Comment by TheHollidayInn** [comment]
Sounds good to me!
