### ISSUE TITLE
Feature: Seek Forward/Backward Buttons

### ISSUE THREAD

**Issue by Tofuus** [SoftwareEngineeringDaily/SEDaily-Android#59]
Something similar to this where the seekbar is moved above or below the play button. Then the seek forward and backward buttons are placed on either side of the play button.

![example](https://i.imgur.com/WcqMXmS.jpg)

I'm not sure how we want to handle icons and such. Do we have someone who can design them? If someone handles the design aspect of this, the implementation would be a pretty good first issue.

**Comment by TheHollidayInn** [comment]
Great suggestion! @themisterholliday might be able to provide us with the icons. If not I can sketch them up.

This feature also depends on the full detail view.

**Comment by Doyniish** [comment]
Any word on where I can get my hands on the icons? Thanks!

**Comment by TheHollidayInn** [comment]
I just use icons from this library: https://github.com/SoftwareEngineeringDaily/SEDaily-Android/blob/4a8a2b77376836b7e4d9818f9d93407f72914793/app/src/main/java/com/koalatea/thehollidayinn/softwareengineeringdaily/MainActivity.java#L135

You can find the list here: https://material.io/icons/
