### ISSUE TITLE
Feature: 1.5 and 2x speed

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/SEDaily-Android#6]
Depends on the Playback feature

**Comment by Tofuus** [comment]
As of API v23 this is natively supported in the Android Media Player https://developer.android.com/reference/android/media/MediaPlayer.html#setPlaybackParams%28android.media.PlaybackParams%29

How should this be implemented in the UI? I'm a fan of how Overcast does it in a through the pull up tab. Should we mimic it?

**Comment by TheHollidayInn** [comment]
Awesome! Two options:

1. Add it to the playback bar
2. Create a a Full Screen player and add the option there: https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/ui/FullScreenPlayerActivity.java

**Comment by Tofuus** [comment]
I'm a fan of the full screen player. I think the playback bar should be kept simple with the 3 buttons that are currently there. The full screen also gives us options to add more cool features. Adaptive playback or captioning maybe?

**Comment by TheHollidayInn** [comment]
Yea, I am down. Let's go with Full screen as well then.

**Comment by TheHollidayInn** [comment]
@Tofuus do you want to work on this feature? It is currently high priority - just to let you know.

**Comment by Tofuus** [comment]
I'm slowly familiarizing with Android. I'm like to pick this up, but if someone more experienced wants to, by all means go ahead.

**Comment by TheHollidayInn** [comment]
A good start would be to replicate the full screen activity above. Start there and see how it goes. I have a few other items I’ll work on first.

**Comment by Tofuus** [comment]
Maybe I'm approaching this wrong but I don't think having an activity is the right way to go. I think it should be a fragment that's part of a SwipeView. But then the podcast details probably needs to go into a fragment to keep the UI similar.

I've been pretty over my head these last couple days trying to learn about ViewPagers and Activities and Fragments. Could you validate that my approach is correct?

**Comment by TheHollidayInn** [comment]
Either approach is fine. I think there is less overhead memory wise with an Activity handling, but that is based on the implementation.

The fragment should not be part of the swipeview. You could create another fragment like the playbackbar. Then, when the play bar is clicked, show full screen view fragment (the same way the playbackbar is shown)
