### ISSUE TITLE
Bug: Crash upon opening episode

### ISSUE THREAD

**Issue by Tofuus** [SoftwareEngineeringDaily/SEDaily-Android#63]
## Device Details
- Device Name: One Plus 5
- Android Version: Android 7.1.1
- App Version: Commit 5bbde60

## Steps to Reproduce:
1. Select latest episode
2. Crash

I'm unsure if it's the latest episode or specifically the Serverless Authentication episode.

https://gist.github.com/anonymous/a2ada765ec5ebb5a1cb8227eebe22e70

**Comment by TheHollidayInn** [comment]
Are you using the Beta build?

**Comment by Tofuus** [comment]
I'm using the latest version of the `develop` branch.

**Comment by samuelrey** [comment]
I was experiencing this earlier today. Not sure what was going on, but it's working fine now.
