### ISSUE TITLE
Bug: Images are not properly displayed in episode description

### ISSUE THREAD

**Issue by Tofuus** [SoftwareEngineeringDaily/SEDaily-Android#64]
## Device Details
- Device Name: One Plus 5
- Android Version: Android 7.1.1
- App Version: Commit 5bbde60

## Steps to Reproduce:
1. Select an episode
2. Gaze up on the glory of green boxes

![](https://i.imgur.com/A4asuDn.png)

This one seems like a pretty good first issue.

**Comment by Amokrane** [comment]
Hey everyone. I am a huge fan of SEDaily and excited to participate in this project. Let me know what you think about my fix here. I think a WebView is more suitable for rendering Html content.

I have tested the fix on a Samsung J3.
![screenshot_2017-11-19-21-04-51](https://user-images.githubusercontent.com/90436/32994914-8796bd1e-cd6d-11e7-82e9-81e12356a769.png)
