### ISSUE TITLE
Project: Add a CODEOWNERS file

### ISSUE THREAD

**Issue by kvithayathil** [SoftwareEngineeringDaily/SEDaily-Android#67]
A small way we can automate some of the reviews process is to have a [Code Owners](https://help.github.com/articles/about-codeowners/) file that defines the default values for reviewing and managing the code e.g. Auto-assigning reviewers for PRs

**Comment by TheHollidayInn** [comment]
Alright, added! Let me know if I need to make any changes. I'm not sure we have much to assign atm.
