### ISSUE TITLE
Crash on Moto X, KitKat

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/SEDaily-Android#76]
## Device Details
- Device Name: Moto X
- Android Version: KitKat
- App Version: 1.1

## Steps to Reproduce:
App crashes on start

**Include screenshots**
![image](https://user-images.githubusercontent.com/1283090/33232579-843da8fe-d1bd-11e7-9460-34bec41b80b5.png)

**Comment by crablar** [comment]
Asked him to update.

**Comment by TheHollidayInn** [comment]
I’m not sure what he means by response, but I have been checking crashes on Crashalytics and pushing updates. I’ll double check this device

**Comment by TheHollidayInn** [comment]
Can you ask if they have the latest version of the app too?

**Comment by crablar** [comment]
All good.

Hassan Farid
 Just updated it - works fine now.thank you for creating an app for amazing content.

**Comment by crablar** [comment]
I'll do that next time before filing a bug.

**Comment by TheHollidayInn** [comment]
Thanks! I’m glad they reached out :)
