### ISSUE TITLE
Project: Add CodeCov coverage badge to README

### ISSUE THREAD

**Issue by kvithayathil** [SoftwareEngineeringDaily/SEDaily-Android#79]
From your CodeCov account, if you go in to your project settings, there should be some options to copy/paste some HTML/Markdown code to display code coverage status (as well as additional options for graphs etc)

**Comment by TheHollidayInn** [comment]
Done https://github.com/SoftwareEngineeringDaily/SEDaily-Android/commit/b7c64e1571a6ac9692c66b48771f48cfdb53380e!
